# Generated by Django 4.0.5 on 2022-07-19 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Birth date'),
        ),
    ]
